name: Build & Release Extension

on:
  push:
    tags:
      - "v*" # runs only when you push a tag like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build --mode cloudflare
        env:
          NODE_ENV: production

      - name: Zip build
        run: |
          cd build
          zip -r ../extension.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
